export const badges = {
  accreditedCentre: {
    primaryText: "CBPD ACCREDITED CENTRE",
    secondaryText: "Accredited – Authorised Centre",
    colors: {
      background: "#E8F5E9",
      border: "#2E7D32",
      iconCircle: "#2E7D32",
      iconFill: "#FFFFFF",
      textPrimary: "#1B5E20",
      textSecondary: "#2E7D32"
    },
    iconType: "tick",
    hoverTooltip: "This badge confirms the institution's current standing within the CBPD framework and is subject to ongoing compliance and review.",
    institutionalDetails: {
      definition: "Awarded to institutions that are fully approved and authorised to deliver CBPD qualifications under the CBPD Qualification Framework (CQF).",
      privileges: [
        "Authorised to deliver CBPD qualifications and programmes",
        "Eligible to issue CBPD-certified awards (via approved systems)",
        "Listed as an official Accredited Centre",
        "Subject to full quality assurance audits and compliance reviews"
      ],
      conditions: [
        "Must maintain QA compliance",
        "Subject to periodic audits and monitoring"
      ]
    }
  },
  approvedPartner: {
    primaryText: "CBPD APPROVED PARTNER",
    secondaryText: "Partner – Recognised Institution",
    colors: {
      background: "#E3F2FD",
      border: "#1565C0",
      iconCircle: "#1565C0",
      iconFill: "#FFFFFF",
      textPrimary: "#0D47A1",
      textSecondary: "#1565C0"
    },
    iconType: "tick",
    hoverTooltip: "This badge confirms the institution's current standing within the CBPD framework and is subject to ongoing compliance and review.",
    institutionalDetails: {
      definition: "Awarded to organisations that have a formal collaboration or partnership agreement with CBPD but may not directly deliver qualifications independently.",
      privileges: [
        "Recognised as an official CBPD Partner Organisation",
        "May support training, recruitment, or academic collaboration",
        "Eligible for co-branded initiatives and programmes"
      ],
      conditions: [
        "Must operate within the scope of partnership agreement",
        "Cannot issue CBPD certifications independently unless authorised"
      ]
    }
  },
  registeredMember: {
    primaryText: "CBPD REGISTERED MEMBER",
    secondaryText: "Member – In Good Standing",
    colors: {
      background: "#F3E5F5",
      border: "#6A1B9A",
      iconCircle: "#6A1B9A",
      iconFill: "#FFFFFF",
      textPrimary: "#4A148C",
      textSecondary: "#6A1B9A"
    },
    iconType: "tick",
    hoverTooltip: "This badge confirms the institution's current standing within the CBPD framework and is subject to ongoing compliance and review.",
    institutionalDetails: {
      definition: "Awarded to organisations that hold active CBPD membership and are recognised within the CBPD network.",
      privileges: [
        "Official recognition as a CBPD Member Organisation",
        "Access to membership benefits and support services",
        "Listed in the CBPD Member Registry"
      ],
      conditions: [
        "Must maintain active membership status",
        "No authority to deliver or issue CBPD qualifications"
      ]
    }
  },
  inactive: {
    primaryText: "CBPD STATUS INACTIVE",
    secondaryText: "Inactive – Not in Good Standing",
    colors: {
      background: "#FDECEA",
      border: "#C62828",
      iconCircle: "#C62828",
      iconFill: "#FFFFFF",
      textPrimary: "#871C1C",
      textSecondary: "#C62828"
    },
    iconType: "cross",
    hoverTooltip: "This badge confirms the institution's current standing within the CBPD framework and is subject to ongoing compliance and review.",
    institutionalDetails: {
      definition: "Applied when an institution's membership, partnership, or accreditation has expired, lapsed, or been suspended."
    }
  },
  pending: {
    primaryText: "CBPD STATUS PENDING",
    secondaryText: "Under Review",
    colors: {
      background: "#F5F5F5",
      border: "#9E9E9E",
      iconCircle: "#9E9E9E",
      iconFill: "#FFFFFF", // assuming the hourglass path uses fill, or it's just general icon color
      textPrimary: "#424242",
      textSecondary: "#757575"
    },
    iconType: "hourglass"
  }
};

export const verificationTemplates = {
  // ----- CERTIFICATE REPORTS -----
  certificate: {
    confirmed: {
      statusTitle: "Confirmed – Authentic Certificate",
      statusIcon: "success",
      messages: [
        "The information provided corresponds with an official certificate record maintained by the Central Board of Professional Development (CBPD).",
        "This certificate is valid, authentic, and in good standing at the time of verification.",
        "The qualification has been duly awarded in accordance with CBPD standards and the CBPD Qualification Framework (CQF)."
      ],
      footer: {
        title: "Standard Footer",
        text: "This verification result has been generated by the official CBPD Digital Certificate Verification System. For further assistance, please contact the Central Board of Professional Development (CBPD) or the approved issuing centre."
      }
    },
    notFound: {
      statusTitle: "No Record Found",
      statusIcon: "error",
      messages: [
        "The submitted details do not match any certificate record within the official CBPD database.",
        "Please ensure that all information entered is accurate, including the certificate number, learner name, learner number, and registration number.",
        "If the issue persists, kindly contact CBPD or the approved issuing centre for further assistance."
      ]
    },
    invalid: {
      statusTitle: "Invalid / Mismatch Detected",
      statusIcon: "warning",
      badge: badges.inactive, // Attach inactive badge
      messages: [
        "The information provided appears to be incomplete or does not correspond with the official CBPD certificate records.",
        "This may be due to discrepancies in the entered details.",
        "Kindly review the information and resubmit. If the issue continues, please contact CBPD for support."
      ]
    }
  },

  // ----- APPROVED CENTRE REPORTS -----
  centre: {
    confirmed: {
      statusTitle: "Confirmed – Approved Centre",
      statusIcon: "success",
      badge: badges.accreditedCentre, // Attach the accredited centre badge
      messages: [
        "The details provided correspond with an official record held by the Central Board of Professional Development (CBPD).",
        "This institution is a CBPD Approved Centre and is currently authorised to deliver CBPD-approved qualifications, subject to continued compliance with CBPD quality assurance and regulatory standards."
      ],
      scope: "Authorised to deliver CBPD qualifications under the CBPD Qualification Framework (CQF), including diploma and certificate programmes as approved.",
      compliance: {
        title: "Quality Assurance & Compliance",
        qaStatus: "Compliant",
        lastAudit: "Successfully Completed",
        regulatoryStanding: "In Good Standing"
      },
      secureVerification: {
        title: "Secure Verification",
        text: "This is a digitally verified record generated through the CBPD Secure Verification System. For additional validation, please refer to the official QR code or digital certificate issued by CBPD."
      },
      officialStatement: {
        title: "Official Statement",
        text: "CBPD Approved Centres are required to operate in accordance with the policies, procedures, and quality assurance framework established by the Central Board of Professional Development (CBPD). Approval is subject to periodic review and ongoing compliance."
      },
      footer: {
        title: "Verification Footer",
        text: "This verification result has been generated by the official CBPD Digital Centre Verification System. For further information or clarification, please contact the Central Board of Professional Development (CBPD)."
      }
    }
  },

  // ----- MEMBERSHIP REPORTS -----
  membership: {
    confirmed: {
      statusTitle: "Confirmed – Valid Membership",
      statusIcon: "success",
      badge: badges.registeredMember, // Attach the registered member badge
      messages: [
        "The details provided correspond with an official membership record maintained by the Central Board of Professional Development (CBPD).",
        "This organisation holds a valid and active CBPD membership and is currently in good standing, subject to ongoing compliance with CBPD standards and requirements."
      ],
      compliance: {
        title: "Compliance & Standing",
        regulatoryStanding: "In Good Standing",
        complianceStatus: "Compliant with CBPD Membership Standards"
      },
      secureVerification: {
        title: "Secure Verification",
        text: "This is a digitally verified membership record generated through the CBPD Secure Verification System. For additional validation, please refer to the official CBPD-issued documentation or QR verification."
      },
      officialStatement: {
        title: "Official Statement",
        text: "CBPD members are required to operate in accordance with the policies, ethical standards, and professional guidelines established by the Central Board of Professional Development (CBPD). Membership is subject to periodic review and continued compliance."
      },
      footer: {
        title: "Verification Footer",
        text: "This verification result has been generated by the official CBPD Digital Membership Verification System. For further information or clarification, please contact the Central Board of Professional Development (CBPD)."
      }
    }
  }
};

/**
 * Calculates remaining days between today and the expiry date
 */
export function calculateRemainingDays(expiryDate: Date | string): number {
  const expiry = new Date(expiryDate);
  const today = new Date();
  const diffTime = expiry.getTime() - today.getTime();
  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
  return diffDays > 0 ? diffDays : 0;
}
