export const verificationTemplates = {
  // ----- CERTIFICATE REPORTS -----
  certificate: {
    confirmed: {
      statusTitle: "Confirmed – Authentic Certificate",
      statusIcon: "success", // Just a hint for frontend UI
      messages: [
        "The information provided corresponds with an official certificate record maintained by the Central Board of Professional Development (CBPD).",
        "This certificate is valid, authentic, and in good standing at the time of verification.",
        "The qualification has been duly awarded in accordance with CBPD standards and the CBPD Qualification Framework (CQF)."
      ],
      footer: {
        title: "Standard Footer",
        text: "This verification result has been generated by the official CBPD Digital Certificate Verification System. For further assistance, please contact the Central Board of Professional Development (CBPD) or the approved issuing centre."
      }
    },
    notFound: {
      statusTitle: "No Record Found",
      statusIcon: "error",
      messages: [
        "The submitted details do not match any certificate record within the official CBPD database.",
        "Please ensure that all information entered is accurate, including the certificate number, learner name, learner number, and registration number.",
        "If the issue persists, kindly contact CBPD or the approved issuing centre for further assistance."
      ]
    },
    invalid: {
      statusTitle: "Invalid / Mismatch Detected",
      statusIcon: "warning",
      messages: [
        "The information provided appears to be incomplete or does not correspond with the official CBPD certificate records.",
        "This may be due to discrepancies in the entered details.",
        "Kindly review the information and resubmit. If the issue continues, please contact CBPD for support."
      ]
    }
  },

  // ----- APPROVED CENTRE REPORTS -----
  centre: {
    confirmed: {
      statusTitle: "Confirmed – Approved Centre",
      statusIcon: "success",
      messages: [
        "The details provided correspond with an official record held by the Central Board of Professional Development (CBPD).",
        "This institution is a CBPD Approved Centre and is currently authorised to deliver CBPD-approved qualifications, subject to continued compliance with CBPD quality assurance and regulatory standards."
      ],
      scope: "Authorised to deliver CBPD qualifications under the CBPD Qualification Framework (CQF), including diploma and certificate programmes as approved.",
      compliance: {
        title: "Quality Assurance & Compliance",
        qaStatus: "Compliant",
        lastAudit: "Successfully Completed",
        regulatoryStanding: "In Good Standing"
      },
      secureVerification: {
        title: "Secure Verification",
        text: "This is a digitally verified record generated through the CBPD Secure Verification System. For additional validation, please refer to the official QR code or digital certificate issued by CBPD."
      },
      officialStatement: {
        title: "Official Statement",
        text: "CBPD Approved Centres are required to operate in accordance with the policies, procedures, and quality assurance framework established by the Central Board of Professional Development (CBPD). Approval is subject to periodic review and ongoing compliance."
      },
      footer: {
        title: "Verification Footer",
        text: "This verification result has been generated by the official CBPD Digital Centre Verification System. For further information or clarification, please contact the Central Board of Professional Development (CBPD)."
      }
    }
  },

  // ----- MEMBERSHIP REPORTS -----
  membership: {
    confirmed: {
      statusTitle: "Confirmed – Valid Membership",
      statusIcon: "success",
      messages: [
        "The details provided correspond with an official membership record maintained by the Central Board of Professional Development (CBPD).",
        "This organisation holds a valid and active CBPD membership and is currently in good standing, subject to ongoing compliance with CBPD standards and requirements."
      ],
      compliance: {
        title: "Compliance & Standing",
        regulatoryStanding: "In Good Standing",
        complianceStatus: "Compliant with CBPD Membership Standards"
      },
      secureVerification: {
        title: "Secure Verification",
        text: "This is a digitally verified membership record generated through the CBPD Secure Verification System. For additional validation, please refer to the official CBPD-issued documentation or QR verification."
      },
      officialStatement: {
        title: "Official Statement",
        text: "CBPD members are required to operate in accordance with the policies, ethical standards, and professional guidelines established by the Central Board of Professional Development (CBPD). Membership is subject to periodic review and continued compliance."
      },
      footer: {
        title: "Verification Footer",
        text: "This verification result has been generated by the official CBPD Digital Membership Verification System. For further information or clarification, please contact the Central Board of Professional Development (CBPD)."
      }
    }
  }
};

/**
 * Calculates remaining days between today and the expiry date
 */
export function calculateRemainingDays(expiryDate: Date | string): number {
  const expiry = new Date(expiryDate);
  const today = new Date();
  const diffTime = expiry.getTime() - today.getTime();
  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
  return diffDays > 0 ? diffDays : 0;
}
